spring:
  datasource:
    hikari:
      username: nu
      password: nu
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:3306/nu?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-stacktrace: always